# Generated by Django 5.2.6 on 2025-09-26 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
            },
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="submitted_at",
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("support", "Technical Support"),
                    ("business", "Business Partnership"),
                    ("feedback", "Feedback"),
                    ("other", "Other"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
    ]
