# Generated by Django 5.2.6 on 2025-09-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_contactmessage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Portfolio Category",
                "verbose_name_plural": "Portfolio Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "short_description",
                    models.CharField(
                        help_text="Short description for portfolio grid", max_length=300
                    ),
                ),
                (
                    "full_description",
                    models.TextField(
                        help_text="Detailed description for portfolio details page"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="Main image for portfolio grid (recommended: 600x400px)",
                        upload_to="portfolio/thumbnails/",
                    ),
                ),
                (
                    "detail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Larger image for detail page (optional)",
                        null=True,
                        upload_to="portfolio/details/",
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=100)),
                ("project_date", models.DateField(blank=True, null=True)),
                (
                    "project_url",
                    models.URLField(blank=True, help_text="Live project URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of technologies (e.g., Django, PostgreSQL, Bootstrap)",
                        max_length=300,
                    ),
                ),
                (
                    "key_features",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show in featured section"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="home.portfoliocategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Item",
                "verbose_name_plural": "Portfolio Items",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "portfolio_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="home.portfolioitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Image",
                "verbose_name_plural": "Portfolio Images",
                "ordering": ["order"],
            },
        ),
    ]
