# Generated by Django 5.2.6 on 2025-09-30 05:16

import apps.demos.salon_booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salon_name",
                    models.CharField(max_length=200, verbose_name="Salon Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        default="default_salon_banner.jpg",
                        null=True,
                        upload_to="demos/salons/banners/",
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "zone",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="District/Zone number",
                        null=True,
                        verbose_name="Zone",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "instagram_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Instagram Link",
                    ),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Telegram Link",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "registered_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registration Date"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="View Count"),
                ),
            ],
            options={
                "verbose_name": "Demo Salon",
                "verbose_name_plural": "Demo Salons",
                "db_table": "demo_salon",
                "ordering": ["-registered_date"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Category Name"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "db_table": "demo_service_category",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SalonAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Amenity Title"),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon Class"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="demos.salon",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon Amenity",
                "verbose_name_plural": "Salon Amenities",
                "db_table": "demo_salon_amenity",
            },
        ),
        migrations.CreateModel(
            name="SalonGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.demos.salon_booking.models.salon_image_upload,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_cover",
                    models.BooleanField(default=False, verbose_name="Cover Image"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="demos.salon",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon Gallery Image",
                "verbose_name_plural": "Salon Gallery Images",
                "db_table": "demo_salon_gallery",
                "ordering": ["order", "-is_cover"],
            },
        ),
        migrations.CreateModel(
            name="SalonReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Customer Name"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Review Comment")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Approved"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="demos.salon",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon Review",
                "verbose_name_plural": "Salon Reviews",
                "db_table": "demo_salon_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Service Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="demos/services/",
                        verbose_name="Service Image",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duration (minutes)"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Base Price",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "salons",
                    models.ManyToManyField(
                        related_name="services",
                        to="demos.salon",
                        verbose_name="Available at Salons",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="demos.servicecategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demo Service",
                "verbose_name_plural": "Demo Services",
                "db_table": "demo_service",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SalonOpeningHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Saturday"),
                            (2, "Sunday"),
                            (3, "Monday"),
                            (4, "Tuesday"),
                            (5, "Wednesday"),
                            (6, "Thursday"),
                            (7, "Friday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Closed"),
                ),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="demos.salon",
                        verbose_name="Salon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salon Opening Hours",
                "verbose_name_plural": "Salon Opening Hours",
                "db_table": "demo_salon_opening_hours",
                "unique_together": {("salon", "day_of_week")},
            },
        ),
    ]
